/** Medical specialties (27+) for doctor assignment and appointment routing. */
export const SPECIALTIES = [
  "General Medicine",
  "Emergency Medicine",
  "Cardiology",
  "Neurology",
  "Pediatrics",
  "Orthopedics",
  "Dermatology",
  "Gynecology",
  "Obstetrics",
  "Psychiatry",
  "Pulmonology",
  "Gastroenterology",
  "Nephrology",
  "Endocrinology",
  "Oncology",
  "Ophthalmology",
  "ENT (Otolaryngology)",
  "Urology",
  "Rheumatology",
  "Hematology",
  "Infectious Disease",
  "Anesthesiology",
  "Radiology",
  "General Surgery",
  "Family Medicine",
  "Nutrition & Dietetics",
  "Physiotherapy",
  "Dentistry",
] as const;
