import { notFound, redirect } from "next/navigation";
import { getSessionProfile } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { Logo } from "@/components/ui/logo";
import { PrintButton } from "@/components/rx/print-button";
import type { RxItem } from "@/app/rx/actions";

export default async function PrescriptionPrintPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const session = await getSessionProfile();
  if (!session?.profile) redirect("/login");

  const supabase = await createClient();
  const { data: rx } = await supabase
    .from("prescriptions")
    .select("*, patient:patients ( full_name, age, gender )")
    .eq("id", id)
    .single();
  if (!rx) notFound();

  const p = rx.patient as unknown as {
    full_name: string;
    age: number | null;
    gender: string | null;
  } | null;
  const items = (rx.items ?? []) as RxItem[];
  const date = new Date(rx.created_at).toLocaleDateString();

  return (
    <div className="min-h-dvh bg-surface-2 px-4 py-8 print:bg-white print:p-0">
      <div className="mx-auto max-w-2xl">
        <div className="mb-4 flex items-center justify-between print:hidden">
          <a href="javascript:history.back()" className="text-sm font-medium text-muted hover:text-foreground">
            ← Back
          </a>
          <PrintButton />
        </div>

        <div className="rounded-2xl border border-border bg-white p-8 text-[#14201b] shadow-card print:rounded-none print:border-0 print:shadow-none">
          <div className="flex items-center justify-between border-b border-[#dbe4de] pb-4">
            <Logo withWordmark />
            <div className="text-right">
              <p className="font-display text-lg font-bold text-[#0f7a57]">Prescription · نسخہ</p>
              <p className="text-sm text-[#5a6b62]">{date}</p>
            </div>
          </div>

          <div className="mt-5 grid grid-cols-2 gap-2 text-sm">
            <p><span className="text-[#5a6b62]">Patient: </span><span className="font-semibold">{p?.full_name ?? "—"}</span></p>
            <p className="text-right">
              {[p?.age != null ? `${p.age} yrs` : null, p?.gender].filter(Boolean).join(" · ")}
            </p>
            {rx.specialty && (
              <p><span className="text-[#5a6b62]">Specialty: </span>{rx.specialty}</p>
            )}
          </div>

          <div className="mt-6">
            <p className="mb-2 font-display text-2xl font-bold text-[#0f7a57]">℞</p>
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-[#dbe4de] text-left text-xs uppercase tracking-wide text-[#5a6b62]">
                  <th className="py-2">Medicine · دوا</th>
                  <th className="py-2">Dose · خوراک</th>
                  <th className="py-2">Frequency · تعدد</th>
                  <th className="py-2">Duration · مدت</th>
                </tr>
              </thead>
              <tbody>
                {items.map((it, i) => (
                  <tr key={i} className="border-b border-[#eef3ef] align-top">
                    <td className="py-2.5 font-semibold">
                      {it.drug}
                      {it.instructions && (
                        <span className="block text-xs font-normal text-[#5a6b62]">{it.instructions}</span>
                      )}
                    </td>
                    <td className="py-2.5">{it.dose ?? "—"}</td>
                    <td className="py-2.5">{it.frequency ?? "—"}</td>
                    <td className="py-2.5">{it.duration ?? "—"}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {rx.advice && (
            <div className="mt-5 text-sm">
              <p className="font-semibold">Advice · مشورہ</p>
              <p className="text-[#45544c]">{rx.advice}</p>
            </div>
          )}
          {rx.follow_up_date && (
            <p className="mt-3 text-sm"><span className="font-semibold">Follow-up · دوبارہ ملاقات: </span>{rx.follow_up_date}</p>
          )}

          <div className="mt-10 flex items-end justify-between">
            <p className="text-xs text-[#7c8b83]">Generated by Greenstar Telehealth · not a substitute for an in-person exam.</p>
            <div className="text-right">
              <div className="mb-1 w-40 border-t border-[#c5d2ca]" />
              <p className="text-sm font-semibold">{rx.doctor_name ?? "Doctor"}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
